del /q c:\OMugs\Running\Violence\MobPlayer\*.*
del /q c:\Omugs\Running\Violence\PlayerMob\*.*
del /q c:\Omugs\Running\Violence\MobStats\Armor\*.*
del /q c:\Omugs\Running\Violence\MobStats\Attack\*.*
del /q c:\Omugs\Running\Violence\MobStats\Damage\*.*
del /q c:\Omugs\Running\Violence\MobStats\Desc1\*.*
del /q c:\Omugs\Running\Violence\MobStats\ExpPoints\*.*
del /q c:\Omugs\Running\Violence\MobStats\HitPoints\*.*
del /q c:\Omugs\Running\Violence\MobStats\Loot\*.*
del /q c:\Omugs\Running\Violence\MobStats\Room\*.*
del /q c:\Omugs\Running\Control\RoomMobMove.txt
del /q c:\Omugs\Running\Control\RoomMobMoveTemp.txt
del /q c:\Omugs\Running\Control\RoomMobList.txt
del /q c:\Omugs\Running\Control\RoomMobListTemp.txt
del /q c:\Omugs\Running\Control\Events\*.*
del /q c:\Omugs\Running\Control\Mobiles\InWorld\*.*
del /q c:\Omugs\Running\Control\Mobiles\NoMove\*.*
del /q c:\Omugs\Running\Control\Mobiles\Spawn\*.*
del /q c:\Omugs\Running\RoomMob\*.*
pause